project:
  type: website
  output-dir: docs
website:
  title: "Maggie M. Dillon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: outreach.qmd
        text: Teaching and Outreach
        
        

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

